### ISSUE TITLE
该项目被废除了？

### ISSUE THREAD

**Issue by emperinter** [charlesXu86/Chatbot_CN#13]
你好！请问该项目已经被废除了吗？没有看到任何的代码和相关说明，网站也没有了。

**Comment by travisgu** [comment]
看起来这个创业公司倒闭了。。。

**Comment by charlesXu86** [comment]
> 看起来这个创业公司倒闭了。。。

没有，只是近期太忙，没有时间来维护项目了。要交付项目，要做产品，还要拉融资
